#!/usr/bin/env Rscript
# 2022.11 Huayun
# This script is used to process hal Liftover results and overlaps them with genomic regions of interests
# This script processes halLiftover results and matches with chip seq peaks
suppressPackageStartupMessages(library(GenomicRanges))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(optparse))
suppressPackageStartupMessages(library(parallel))


# parse arguments ---------------------------------------------------------
option_list <- list(
  make_option(c("-i", "--input-file"), 
              help="Input file specifiying species and path to liftover output, and path to peak files "),
  make_option("--peaks", help = "two-column, tab-deliminated file specifying species and peak files, generated by wrapper script"),
  make_option(c("-f", "--factor"),  
              help="The TF/factor being analyzed"),
  make_option(c("-m","--maxmin"), default = "0:1", help="Maxgap:Mininum overlap between orthologous regions and peaks, in bp [default %(default)s]"),
  make_option(c("-s", "--stitchbp"),type="integer", default=2, 
              help="Stitching orthologous regions within how many bps [default %(default)s]"),
  make_option(c("-p", "--return-num-paralogs"), action = "store_true", default = FALSE,
              help = "If to return the number of paralogous regions"),
  make_option(c("-t", "--threads"), default = 4,
              help = "number of threads to use")
  
)
opt_parser <- OptionParser(option_list=option_list)
args <- parse_args(opt_parser)


input_file = args$`input-file`
peak_file = args$peaks
tf = args$factor
stitchbp = args$stitchbp ## Compara often reports regions with small gaps (1bp). Regions separated by <= stitchbp will be merged
maxgap = as.numeric(unlist(strsplit(args$maxmin, ":"))[1])
minovl = as.numeric(unlist(strsplit(args$maxmin, ":"))[2])

threads = args$threads


# testing -----------------------------------------------------------------

# setwd("/mnt/mdwilson/huayun/others/hal_vs_epo/hal_zoonomia/")
# 
# input_file = "/mnt/mdwilson/huayun/others/hal_vs_epo/hal_zoonomia/zoochip/ONECUT1_rscript_input.txt"
# peak_file = "/mnt/mdwilson/huayun/others/hal_vs_epo/hal_zoonomia/zoochip/ONECUT1_peakfiles.txt"
# 
# maxgap=0
# minovl=1
# stitchbp=2
# tf = "ONECUT1"
# 
# 
# 
# anchor_species <- "Homo_sapiens"
# query_species <- "Mus_musculus"



# anchor species: here is means the reference species
# query species: the species to compare to
# Note that regions (peaks) in query species are lifted to target species

# by default analysis is done from all species' perspective 

# functions ---------------------------------------------------------------

regions_to_grlist <- function(region_df, label){
  region_gr <- makeGRangesFromDataFrame(region_df, keep.extra.columns = T)
  # split into list by anchor peak and stitch regions next to each other
  region_gr_list <- GenomicRanges::reduce(split(region_gr, region_gr$anchor_oriPeak, drop = F), min.gapwidth = stitchbp)
  region_gr_list <- region_gr_list[unique(region_gr$anchor_oriPeak)]
  # flatten the list, add query species peak names and resplit into lists
  region_gr_unlisted <- unlist(region_gr_list)
  mcols(region_gr_unlisted)[paste0(label,"_liftedGr")] <- with(region_gr_unlisted, paste0(label,".",seqnames, ":", start, "-", end))
  region_gr_list <- split(region_gr_unlisted, names(region_gr_unlisted), drop = F)
  return(region_gr_list)
}


# read in species peak match
species_peaks <- read.table(peak_file, sep = "\t", col.names = c("species","peak"))
species_list <- species_peaks$species

# Get a list of GRanges for original peaks --------------------------------

original_peaks <- apply(species_peaks,1, function(x){ ## Read in original peak file. Order is the same as in the compara_regions file
 #peak_file <- paste0("peaks/",species_map[anchor_species],"_tnf_peaks.tsv") # temp solution
  ##############################################
  
  species <- x[1]
  peak_file <- x[2]
  
  # for testing
  #peak_file <- gsub("/home/huayun|/hpf/largeprojects","/mnt", peak_file)
  if(!file.exists(peak_file)){
    stop(paste("peak file", peak_file, "does not exist"))
  } else{
    
    peaks <- read.table(peak_file, header = T, col.names = c("seqnames", "start", "end", "strand")) [,1:3]
    peaks$oriPeak <- paste0(species, ".", peaks$seqnames,":", peaks$start,"-", peaks$end)
    peak.ranges <- makeGRangesFromDataFrame(peaks, keep.extra.columns = T)
  }
})
names(original_peaks) <- species_peaks$species


# read in hal liftover results --------------------------------------------

liftover_results <- read.table(input_file, sep = "\t", col.names = c("target","query","result_file"))


compara_list <- lapply(species_list, function(anchor_species){
  print(paste("Processing liftover Regions for:", anchor_species))
  other_species_list <- species_list[species_list != anchor_species]
  
  # Process all the liftover results for the anchor species
  compara_species_process_out <- lapply(other_species_list, function(query_species){
    print(query_species)
    liftover_file <- subset(liftover_results, target == anchor_species & query == query_species)$result_file
    
    # for testing
  #  liftover_file <- gsub("/home/huayun|/hpf/largeprojects","/mnt", liftover_file)
    
    if(!file.exists(liftover_file)){
      stop(paste("liftover result file", liftover_file, "does not exist"))
    } else{
      lift <- read.table(liftover_file, header = T, stringsAsFactors = F, as.is = T) %>%
        dplyr::select(seqnames = dest_chr, start = dest_start, end = dest_end, src_chr, src_start, src_end) 
      lift$anchor_oriPeak <- paste0(anchor_species, ".", lift$src_chr,":", lift$src_start,"-", lift$src_end)
    return(regions_to_grlist(lift, query_species))
    }
  })
  #compara_species_grs <- lapply(compara_species_process_out, "[[", 1)
  names(compara_species_process_out) <- other_species_list
  return(compara_species_process_out)
})
names(compara_list) <- species_list


# Overlap orthologous regions and peaks -------------------------------------------------------------

compara_matched_list <- lapply(species_list, function(anchor_species){
  print(paste("Processing region match for:", anchor_species))
  other_species_list <- species_list[species_list != anchor_species]
  
  match_one_species <- lapply(other_species_list, function(query_species){
    print(paste("Processing region match for target species:", anchor_species, "and query species:", query_species))
    
    # example: anchor species: human, query species: mouse
    anchor_species_ori_peaks <- original_peaks[[anchor_species]] # original peak regions from anchor species. E.g. human peaks
    query_species_lifted_regions <- compara_list[[query_species]][[anchor_species]] # peaks in query species lifted over to the anchor species. E.g. mouse peaks lifted over to human regions, one mouse peak may result in multiple regions 
    
    # find overlap between anchor species peaks and query species peaks that are lifted over to the anchor species genome
    query_lift2_ol_anchor <- findOverlaps(anchor_species_ori_peaks, query_species_lifted_regions, maxgap=maxgap, minoverlap=minovl)
    
    conserved_pks <- as.data.frame(query_lift2_ol_anchor)
    # associate the overlap with the original query species peaks 
    conserved_pks$query_oriPeak <- names(query_species_lifted_regions[conserved_pks$subjectHits])
    
    # construct a vector recording anchor species peak conservation levels, label everything as X
    out <- rep("X", length(anchor_species_ori_peaks))
    names(out) <- anchor_species_ori_peaks$oriPeak
    
    # if the anchor species peak can be lifted over to query species (human to mouse), label as 0
    out[names(out) %in% names(compara_list[[anchor_species]][[query_species]])] <- 0
    
    # if peaks lifted over from query species overlap with anchor species peaks, label as 1
    out[conserved_pks$queryHits] <- 1
    out_df <- enframe(out)
    
    # construct output
    species_con_out <- as.data.frame(anchor_species_ori_peaks)["oriPeak"] %>% 
      mutate(index = seq(1:nrow(.))) %>% 
      left_join(out_df, by = c("oriPeak" = "name")) %>% 
      left_join(conserved_pks, by = c("index" = "queryHits")) %>% 
      rename(ori_peak = oriPeak, matched_peaks = query_oriPeak) %>% 
      dplyr::select(-index) %>% 
      group_by(ori_peak) %>% 
      summarise(out = unique(value), matched_peaks = paste(unique(matched_peaks), collapse = ";")) %>% 
      setNames(.,c("oriPeak",
                   paste0(query_species, "_conStatus"),
                   query_species))
    return(species_con_out)
    })
  
  match_one_species_out <- match_one_species %>% 
    reduce(left_join, by = "oriPeak") %>% 
    unite("conservation", ends_with("_conStatus"), sep = "") %>% 
    separate(oriPeak, sep = "([\\.\\:\\-])", into = c(NA, "seqnames", "start", "end")) %>% 
    dplyr::select(seqnames, start, end, conservation, !!other_species_list, everything())
  
  write.table(x=match_one_species_out,
              file=paste0(tf,"max",maxgap,"min",minovl,"_peakConservation_",anchor_species,"_halLiftover.txt"),
              row.names=F, quote=F, sep="\t")
  return(match_one_species_out)
})
  
names(compara_matched_list) <- species_list

  




